### PR TITLE
Error if pydo add is run without providing a title

### LINKED ISSUE #65: Add task with no title error
The `add` command throws `TypeError: add() missing 1 required positional argument: 'title'` if no title is passed, it would be nice to raise a custom error.

### PR DESCRIPTION
**Pull request by m0wer**
Explained in #65. Fixes #65. Not ready for merge yet because it breaks some tests.

### CODE REVIEW

**Comment by lyz-code** [comment]
LGTM your changes. 

I was afraid this would happend after the `main()` definition change, but I can't see why has it changed after it was merged.

Such a simple change and all that it breaks (through improving it xD)

**Comment by m0wer** [comment]
@lyz-code this is almost ready, but I need some advice on how to approach these tests:

https://github.com/lyz-code/pydo/blob/8e52f5376e66af12ebdd42dc2c38c88f6e3005d7/tests/test_init.py#L77
https://github.com/lyz-code/pydo/blob/8e52f5376e66af12ebdd42dc2c38c88f6e3005d7/tests/test_init.py#L98

Should I catch the `ValueError` rised because the `add` command doesn't get the required `title` attribute? Should I add the `title` attribute if the subcommand is `add`? I don't love either of these approaches though, any other ideas?

**Comment by lyz-code** [comment]
@m0wer I'd either remove the forced requirement of the title or add it in the test if we decide it should be enforced. If it's difficult with the parametrize, copy and paste the test and particularize it only for the add case

**Comment by m0wer** [comment]
> @m0wer I'd either remove the forced requirement of the title or add it in the test if we decide it should be enforced. If it's difficult with the parametrize, copy and paste the test and particularize it only for the add case

I mean, it should be enforced since it's a necessary attribute for a task right?
https://github.com/lyz-code/pydo/blob/5a965856d6adfaef363477c0a53db9517c7cf97f/pydo/models.py#L65

**Comment by m0wer** [comment]
Ping @lyz-code.

**Comment by lyz-code** [comment]
Sorry @m0wer , I leave it up to you. Should it be a necessary attribute? if so take one decission, if not the other

**Comment by lyz-code** [comment]
It no longer applies, with 0.1.0 it has been solved already.

Thanks for your contribution though :)

**Pull request closed without merging**
